### ISSUE TITLE
Task 2 - Step 13

### ISSUE THREAD

**Issue by tsander26** [Microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics#15]
This step states: "As an experiment, scale the number of requested RU/s for your Cosmos DB collection down to 750. After doing so, you should see increasingly slower transfer rates to Cosmos DB due to throttling. You will also see the pending queue growing at a higher rate. The reason for this is because when the number of writes (remember, writes use 5 RU/s vs. just 1 RU/s for reads) exceeds the allotted amount of RU/s, Cosmos DB sends a 429 response with a retry_after header value to tell the consumer that it is resource-constrained. The SDK automatically handles this by waiting for the specified amount of time, then retrying. After you are done experimenting, set the RU/s back to 15,000."

I like this exercise and this paragraph. However, writes do not always use 5 RU/s and reads do not always use 1 RU/s. This is typical write/read performance for a 1 KB document but larger documents will consume more RU's.

**Comment by joelhulen** [comment]
Ah yes, I forgot to specify that 5 RU/s write and 1 RU/s read is based on 1 KB-sized documents. I do say this in the whiteboard design session. I can add this distinction to this paragraph and clarify the statement with "typically" or similar, if that's OK, or just take that part out. Thoughts?
