### ISSUE TITLE
Sign off received - please finalize workshop

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics#16]
@ZoinerTejada @joelhulen 
Hello,
Our tech lead has signed off, please review feedback and finalize this workshop. Let me know when it's ready for QC/publishing.

**Comment by joelhulen** [comment]
Doing this now. Thank you.

**Comment by joelhulen** [comment]
The workshop has been finalized and all issues closed.
