### ISSUE TITLE
ARM Script

### ISSUE THREAD

**Issue by srchi** [microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics#17]
Please make sure we have an ARM script to deploy resources for this lab.

**Comment by Zingonead** [comment]
there is a problem with the eventhub connection string 
we had to add the EntityPath in it first

when running the application the following error appears 

"Event Hubs request <number> eventually failed with: Put token failed. status-code: 404, status-description: The messaging entity 'sb://woodgrove-events.servicebus.windows.net/woodgrove-events' could not be found. TrackingId:51ebabc3-1f2e-4644-890f-dbdb1e78b772_G1, SystemTracker:woodgrove-events.servicebus.windows.net:woodgrove-events, Timestamp:2019-05-03T11:11:50. "

**Comment by joelhulen** [comment]
The ARM template is now part of the lab.
