### ISSUE TITLE
Issue in Before Hands On Lab Task 13

### ISSUE THREAD

**Issue by Abhishekpathania01** [Microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics#19]
[Task 13 Create an Azure Data Lake Storage Gen2 account](https://github.com/Microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Cosmos%20DB%20real-time%20advanced%20analytics.md#task-13-create-an-azure-data-lake-storage-gen2-account) We should create Azure Data Lake Storage Gen2 , but as per the mentioned steps and screenshots storage account with kind StogareV2 is been creating. 
Could you please look into this and update?

Thanks
Abhishek

**Comment by joelhulen** [comment]
@kylebunting, can you look into this?

**Comment by kylebunting** [comment]
Abhishek, Azure Data Lake Storage Gen2 is provisioned through a storage account. Step for under Task 13 has you add a hierarchical namespace, which is leads to the storage account being provisioned as an ADLS Gen2 resource.
