### ISSUE TITLE
import azureml fails

### ISSUE THREAD

**Issue by Briwalkr** [Microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics#22]
Working through this lab, I got to exercise 3 notebook 1-Prepare-Scoring-Web-Service, and I ran into an error in the "Deploy Model" step. The code is as follows: 
import azureml
from azureml.core import Workspace
from azureml.core.model import Model

I receive the following error.

ImportError: No module named 'azureml'
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<command-1485802949688086> in <module>()
----> 1 import azureml
      2 from azureml.core import Workspace
      3 from azureml.core.model import Model

ImportError: No module named 'azureml'

My cluster configuration is as follows: 
5.2 (includes Apache Spark 2.4.0, Scala 2.11)
Python 3
spark.databricks.delta.preview.enabled true

I also tried running on ADB 5.1  (includes Apache Spark 2.4.0, Scala 2.11)
Python 3
spark.databricks.delta.preview.enabled true
as specified in the setup module, but I got the same results. 

Can you advise as to the appropriate cluster configuration or location of the azureml module? I tried installing the azureml library from CRAN, but it fails with the following error:
java.lang.RuntimeException: Installation failed with message: 

Error installing R package: Could not install package with error: 1: package ‘azureml’ is not available (for R version 3.4.4) 

I got this error with both of the above cluster configurations.

any help would be appreciated.

**Comment by joelhulen** [comment]
Is the `azureml-sdk[automl_databricks]` library installed on your cluster, per [Exercise 3, Task 1](https://github.com/Microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Cosmos%20DB%20real-time%20advanced%20analytics.md#task-1-install-the-azureml-and-scikit-learn-libraries-in-databricks)?

**Comment by DawnmarieDesJardins** [comment]
Assuming resolved and closing.  @Briwalkr Please reopen if necessary.
