### ISSUE TITLE
Exercise2 Task 1: App Registration options got updated in Azure Portal

### ISSUE THREAD

**Issue by Abhishekpathania01** [Microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics#23]
[In Exercise 2 Task 1](https://github.com/Microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Cosmos%20DB%20real-time%20advanced%20analytics.md#task-1-create-a-service-principal-for-oauth-access-to-the-adls-gen2-filesystem) There is a task to create a "+New application registration" under App registrations, but due to updates in Azure Portal, we have to do those steps under App registration (Legacy):
![image](https://user-images.githubusercontent.com/38715522/57087025-d580a300-6d1c-11e9-97f3-60ef3a4126e8.png)
only under App registration (Legacy) we have the right options. 

Can you please check and fix this ASAP, we have workshop scheduled next week. Please fix this in lab guide. 

Thanks,
Abhishek

**Comment by DawnmarieDesJardins** [comment]
@kylebunting 
Hi Kyle, can you please review and advise?  Thanks! Dawnmarie

**Comment by kylebunting** [comment]
I've submitted a pull request to fix this issue. I updated the HOL step-by-step guide to use the Azure CLI to create the service principal, so this won't be an issue with the screen shots.

@DawnmarieDesJardins, please review and merge the pull request to close this issue.

**Comment by DawnmarieDesJardins** [comment]
Closing with recent PR/merge
