### ISSUE TITLE
Events Hubs Request Failed

### ISSUE THREAD

**Issue by Zingonead** [microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics#25]
There is a problem with the eventhub connection string
We had to add the EntityPath in it first

when running the application the following error appears

"Event Hubs request eventually failed with: Put token failed. status-code: 404, status-description: The messaging entity 'sb://*****-*****.servicebus.windows.net/woodgrove-events' could not be found. TrackingId:51ebabc3-1f2e-4644-890f-dbdb1e78b772_G1, SystemTracker:woodgrove-events.servicebus.windows.net:woodgrove-events, Timestamp:2019-05-03T11:11:50. "

**Comment by joelhulen** [comment]
@Zingonead Did you grab the connection string from the Sender policy that you added to the new event hub (not the Event Hubs namespace), as shown in Step 16 here? https://github.com/Microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Cosmos%20DB%20real-time%20advanced%20analytics.md#task-13-provision-event-hubs

**Comment by Zingonead** [comment]
Yes 

Adriano Zingone

On 3 May 2019, at 15:49, Joel Hulen <notifications@github.com> wrote:

@Zingonead Did you grab the connection string from the Sender policy that you added to the new event hub (not the Event Hubs namespace), as shown in Step 16 here? https://github.com/Microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Cosmos%20DB%20real-time%20advanced%20analytics.md#task-13-provision-event-hubs

**Comment by joelhulen** [comment]
I just created a new EH namespace and an event hub within. I created the Sender policy, and the connection string to this policy contains the entity path, as expected.

Does your connection string look similar to the following?

`Endpoint=sb://jdhtest.servicebus.windows.net/;SharedAccessKeyName=Sender;SharedAccessKey=[REDACTED];EntityPath=transactions`

**Comment by DawnmarieDesJardins** [comment]
@Zingonead 
Hello!  Checking in with you to see if you've been able to move ahead and we can close this open issue.
Thanks, Dawnmarie

**Comment by joelhulen** [comment]
Closing due to lack of feedback. Feel free to re-open if you are still having the issue.
