### ISSUE TITLE
Exercise.2: Task 10- Error in Notebook

### ISSUE THREAD

**Issue by SeeratArora** [microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics#33]
HOL step-by step guide, Exercise.2: Task 10- Cosmos-DB-Change Feed is giving error on running command no.4.
It was working fine 2 days ago but after the updates where it got updated 9 hours ago today, it is giving error in the above mentioned notebook.

![Error_nb_cosmos](https://user-images.githubusercontent.com/50323628/58168718-8b9c3480-7cac-11e9-8725-463cf39704f3.jpeg)

**Comment by joelhulen** [comment]
Could you please clarify the following?

1. Did you start from scratch this morning, or are you using a cluster that you set up 2 days ago?
2. If you are using the same cluster from 2 days ago, did you re-import the DBC file (notebooks) this morning?
3. If you go to the Libraries tab for your cluster, which libraries do you have loaded?

This notebook was not modified 9 hours ago. Only the notebooks within the Exercise 3 folder.

**Comment by SeeratArora** [comment]
Clarification on your points:

1. Yes I started from scratch today and created new cluster.
2. With a new cluster I re-imported new DBC file.
3. Libraries Loaded- azure-cosmosdb-spark_2.4.0_2.11.

**Comment by joelhulen** [comment]
What version of Databricks and Spark are you running on the new cluster?

**Comment by joelhulen** [comment]
You have an UnknownHostException. You may need to double-check the value for `ADLS-Gen2-Account-Name` in Key Vault. Also, open your storage account and verify there is a top-level folder named `transactions`.

**Comment by SeeratArora** [comment]
Yes I cross-checked the versions and storage account name. By mistake there was an empty space with storage account name in key-vault. That's why it was giving error. I corrected and it's working fine.
Thanks for your quick help and support.

**Comment by joelhulen** [comment]
Ah, great. Glad you are up and running. Also, glad to help :)
