### ISSUE TITLE
Failing on spark.sql("SELECT * FROM transactions")

### ISSUE THREAD

**Issue by sqlshep** [microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics#34]
I will be the first to admit i probably missed a step, but i went through the notebooks twice. 

Exercise 4 - Task 3: Distributing batch scored data globally using Cosmos DB

Where is the delta table created? 

--Load transactions from the Delta table into a Spark DataFrame
transactions = spark.sql("SELECT * FROM transactions")

Fails with 

AnalysisException: 'Table or view not found: transactions; line 1 pos 14'
---------------------------------------------------------------------------
AnalysisException                         Traceback (most recent call last)
<command-3215518441927715> in <module>()
      1 # Load transactions from the Delta table into a Spark DataFrame
----> 2 transactions = spark.sql("SELECT * FROM transactions")
      3 
      4 # Get a Pandas DataFrame from the Spark DataFrame
      5 pandas_df = transactions.toPandas()

**Comment by joelhulen** [comment]
The `transactions` Delta table is created within the `2-Cosmos-DB-Change-Feed` notebook under the **Exercise 2** folder, cell 15.

![image](https://user-images.githubusercontent.com/5950304/58599110-cc67f080-824c-11e9-8bfa-f23f149a2156.png)

Were you able to successfully run the above notebook? Did you also make sure you set your ADLS Gen2 storage name in that cell?

**Comment by sqlshep** [comment]
Got it, i did not look far enough back for the table.  The cluster was reset before i finished the MCW, so it dropped the table.
