### ISSUE TITLE
Exercise 2 Task 10: Issue in running Exercise 2 Notebook named 2-Cosmos-DB-Change-Feed.

### ISSUE THREAD

**Issue by Abhishekpathania01** [microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics#36]
Hi @joelhulen I am running doing this lab and having issue with running the Notebooks [Exercise 2-Cosmos-DB-Change-Feed](https://github.com/microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Cosmos%20DB%20real-time%20advanced%20analytics.md#task-10-responding-to-streaming-transactions-using-the-cosmos-db-change-feed-and-spark-structured-streaming-in-azure-databricks)

Mainly I am facing issue with **CMD 29** Spark jobs are running and taking long time to execute ( around more than 40 minutes and still in running state). 

![image](https://user-images.githubusercontent.com/38715522/65830708-935d8c80-e2cf-11e9-9a00-22441d50dd4a.png)

Could you please help me with resolving this? ( any suggestion will be helpful) I can share the environment details with you, if needed so that you can quickly look into this. 

Thanks,
Abhishek

**Comment by joelhulen** [comment]
You are running a streaming query. It will run indefinitely until you stop the stream. it watches the Cosmos DB Change Feed, and will process data writing to the container in real time. Run the generator while this cell is running, then execute the cells below this one to view the data stored in Delta.

**Comment by Abhishekpathania01** [comment]
Thanks @joelhulen Will try this out.

**Comment by joelhulen** [comment]
@Abhishekpathania01 I am closing this issue. Please feel free to re-open it if you are still encountering any issues.

**Comment by SeeratArora** [comment]
Hi @joelhulen 

In [Exercise 3: Task 2: "https://github.com/microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Cosmos%20DB%20real-time%20advanced%20analytics.md#task-2-prepare-and-deploy-scoring-web-service"]

**Comment by SeeratArora** [comment]
Hi @joelhulen 

In [Exercise 3: Task 2: Prepare and deploy scoring web service](https://github.com/microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Cosmos%20DB%20real-time%20advanced%20analytics.md#task-2-prepare-and-deploy-scoring-web-service)
![image](https://user-images.githubusercontent.com/50323628/66128048-ab544980-e60a-11e9-80b1-5cad2d9d1e73.png)
)

cmd 7 is giving error that says: **No module named 'pandas'**.
Could you please check this, we have a workshop scheduled on 10/11.

Thanks.

**Comment by joelhulen** [comment]
@SeeratArora I'll test this out and fix any issues over the next few days.

**Comment by SeeratArora** [comment]
Hi @joelhulen 
Do we have any updates on this? We've a workshop scheduled on 10/11.

**Comment by joelhulen** [comment]
@SeeratArora I'm working on this today.

**Comment by joelhulen** [comment]
@SeeratArora I've merged my changes. Could you please re-import the notebooks and try again? Before running the new version of the notebooks, follow the new cluster creation instructions and each step that follows. So, delete the notebooks you previously imported, then start following the guide at Exercise 2, Task 5. (You do not need to set up the Databricks Key Vault-backed secrets.)
