### ISSUE TITLE
The deployment of the Model to ACI Fails with the following error

### ISSUE THREAD

**Issue by fnaadb** [microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics#40]
Message: Service deployment polling reached non-successful terminal state, current service state: Transitioning:

Error:
{
  "statusCode": 400,
  "code": "EnvironmentBuildFailed",
  "message": "Failed Building the Environment."
}
	InnerException None
	ErrorResponse 
{
    "error": {

**Comment by joelhulen** [comment]
@fnaadb I'll take a look at this today.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #41
