### ISSUE TITLE
Exercise 3: Task 2: Notebook 2-Prepare-Batch-Scoring-Model-cmd 98 failing

### ISSUE THREAD

**Issue by SeeratArora** [microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics#42]
[Exercise 3: Task 2:](https://github.com/microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Cosmos%20DB%20real-time%20advanced%20analytics.md#task-2-prepare-batch-scoring-model) Notebook 2-Prepare-Batch-Scoring-Model, cmd 98 is failing as shown below:

![image](https://user-images.githubusercontent.com/50323628/80255839-5c9bf900-869b-11ea-87de-64b72c8b2d06.png)

Can you please have a look into this?

Thanks,
Seerat

**Comment by joelhulen** [comment]
I've updated the notebooks to fix this issue. You will need to go back and create a new cluster, following the updated instructions. You will also need to create a new Cosmos DB Spark library that uses the updated library version, per the new instructions.
