### ISSUE TITLE
Secure String in Program.cs Line 433

### ISSUE THREAD

**Issue by carlneal** [microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics#43]
I had to add a method to converet the secure string before passing to the new DocumentClient method.  May want to incorporate this fix.

Also I needed to add the following to get the connectionPolicy to work
private static ConnectionPolicy connectionPolicy;

using System.Security;
.
.
.

using (_cosmosDbClient = new DocumentClient(new Uri(arguments.CosmosDbEndpointUrl), ConvertToSecureString(arguments.CosmosDbAuthorizationKey), connectionPolicy))
            {
.
.
.
.
 private static SecureString ConvertToSecureString(string password)
        {
            if (password == null)
                throw new ArgumentNullException("password");

            var securePassword = new SecureString();

            foreach (char c in password)
                securePassword.AppendChar(c);

            securePassword.MakeReadOnly();
            return securePassword;
        }
.
.
}

**Comment by joelhulen** [comment]
I've updated the code to use the new secure string method (thank you for that)!

However, I did not add the static reference the `ConnectionPolicy`. You add a new `ConnectionPolicy` in TODO 6: `// TODO 6: Complete the code below to create a Cosmos DB connection policy that has a Direct Connection Mode and uses the TCP Connection Protocol.`, (line 372)
