### ISSUE TITLE
Ex2, Task5, Step2 throws NameError: name 'data_path' is not defined

### ISSUE THREAD

**Issue by paulburpo** [microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics#46]
Exercise 2, Task 5, Step 2

This line of code

    transactions = data_path

Throws *"NameError: name 'data_path' is not defined"* 

Based on the screenshots it looks like this is a change in the auto-generated code. It now uses "df" instead of "data_path".

So technically the screenshots are out of date and the steps to generate the notebook is a little different as well (can probably wait for next test/fix). 

I am testing this on an AERS subscription so might be different for normal subs.

**Comment by DawnmarieDesJardins** [comment]
@joelhulen @timahenning 
Hello!  Any update on this one?  Thank you!

**Comment by joelhulen** [comment]
@DawnmarieDesJardins , I've been holding off on this one since Synapse Analytics is undergoing a lot of UI changes leading into the GA release next week. Is it OK if I fix this at the beginning of the week, once the UI changes have settled?

**Comment by DawnmarieDesJardins** [comment]
@joelhulen
Of course, thanks for letting us know! I wasn't aware there were changes coming.

**Comment by paulburpo** [comment]
Sounds like a good plan to me. Thanks!

**Comment by opsgilitybrian** [comment]
I'm just running through this and it looks like the df column names are all lost too.

For example, I think 
`transactions.groupBy("cvvVerifyResult").count().sort("cvvVerifyResult").show()`
becomes
`transactions.groupBy("_c35").count().sort("_c35").show()`

![image](https://user-images.githubusercontent.com/66644214/101215845-1c92f080-3644-11eb-89cc-42e6381ea1fd.png)

So maybe there is a way to map those columns to get better naming?

**Comment by joelhulen** [comment]
Working on this and the other issue. I'll let you know once it is fixed.
