### ISSUE TITLE
Deploy error

### ISSUE THREAD

**Issue by ysaka59** [microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics#52]
Thank you for fixing #51 but unfortunately there is a new error.

{
"status": "Failed",
"error": {
"code": "InvalidTemplate",
"message": "行 '476'、列 '9' のリソース '/subscriptions/09322f29-9523-4776-9f1b-f70a10f0eaeb/resourceGroups/MCW-Cosmos-DB-Real-Time-Advanced-Analytics/providers/Microsoft.Resources/deployments/UpdateSparkPool01' に対するテンプレート言語の式を処理できません。'The template variable 'location' is not found. Please see https://aka.ms/arm-template/#variables for usage details.'",
"additionalInfo": [
{
"type": "TemplateViolation",
"info": {
"lineNumber": 476,
"linePosition": 9,
"path": ""
}
}
]
}
}

**Comment by joelhulen** [comment]
Fixed. Azure went down during testing earlier.
