### ISSUE TITLE
Issue in Exercise -1, Task -4

### ISSUE THREAD

**Issue by Shivashant25** [microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics#56]
In exercise -1> task -4> step -37, I didn't find the `ttl` value in any of the items. I had set Time to Live as On (no default) option under Scale & Settings blade in data explorar. But I didn't get the expected output.

![image](https://user-images.githubusercontent.com/81952290/126298101-2f44a73a-407c-4004-80b7-1b2be340fdc8.png)

**Comment by joelhulen** [comment]
Can you confirm that you successfully modified `Transaction.cs` by completing TODO #7: `tx.TimeToLive = 60 * 60 * 24 * 60;`?

Also, you initially ran the script without TTL, so those documents will not have the entry. Try sorting the documents in Cosmos DB by `_ts` in descending order to see the most recent documents first. Take a look at them and see whether the TTL property is set.

**Comment by Shivashant25** [comment]
Hi @joelhulen , I tried ordering the items in descending order in the data explorer. I was able to see `ttl` value. The issue is fixed and we are good with this lab. Closing this issue. Thank you.
