### ISSUE TITLE
Before hands on needs to update.

### ISSUE THREAD

**Issue by sumitmalik51** [microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics#61]
We need to have a VM in the template with all the pre-req installed because in the lab we are using some application that needs to be installed to run through the lab.

1. VM should be with VS 2019.
2. .net 5 SDK should be installed.

In the before hands-on lab, it is not mentioned anywhere that we need to have VM with VS 2019 and .NET [SDK,](url) and that is causing confusion.

Thanks

**Comment by DawnmarieDesJardins** [comment]
@joelhulen 
Hello!  I know you're working on this, can you give an ETA for a fix?
Much appreciated, Dawnmarie

**Comment by joelhulen** [comment]
@DawnmarieDesJardins I have submitted a PR to close this issue. Please review and merge.
