### ISSUE TITLE
Issue in Exercise 3, task 2

### ISSUE THREAD

**Issue by Kalyani7744** [microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics#65]
In [Exercise 3, task 2, step 8](https://github.com/microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics/blob/main/Hands-on%20lab/HOL%20step-by%20step%20-%20Cosmos%20DB%20real-time%20advanced%20analytics.md#task-2-prepare-and-deploy-scoring-web-service), while installing libraries using  **!pip install**, pyldevis library installation is getting failed with multiple errors as shown below.

![image](https://user-images.githubusercontent.com/83349665/150381512-20ec82ae-180f-4b6c-a38d-7a16e66a3a90.png)

**Below is the complete error message:**

ERROR: pyldavis 3.3.1 requires sklearn, which is not installed.
ERROR: responsibleai 0.15.0 has requirement interpret-community>=0.22.0, but you'll have interpret-community 0.21.0 which is incompatible.
ERROR: raiwidgets 0.15.0 has requirement ipython==7.16.1, but you'll have ipython 7.16.2 which is incompatible.
ERROR: raiwidgets 0.15.0 has requirement jinja2==2.11.3, but you'll have jinja2 2.11.2 which is incompatible.
ERROR: pyldavis 3.3.1 has requirement numpy>=1.20.0, but you'll have numpy 1.18.5 which is incompatible.
ERROR: pyldavis 3.3.1 has requirement pandas>=1.2.0, but you'll have pandas 0.25.3 which is incompatible.
ERROR: pycaret 2.3.5 has requirement lightgbm>=2.3.1, but you'll have lightgbm 2.3.0 which is incompatible.
ERROR: pycaret 2.3.5 has requirement numpy==1.19.5, but you'll have numpy 1.18.5 which is incompatible.
ERROR: pycaret 2.3.5 has requirement scikit-learn==0.23.2, but you'll have scikit-learn 0.24.2 which is incompatible.
ERROR: azureml-train-automl-runtime 1.36.0 has requirement scikit-learn<0.23.0,>=0.19.0, but you'll have scikit-learn 0.24.2 which is incompatible.
ERROR: azureml-responsibleai 1.37.0 has requirement azureml-core~=1.37.0, but you'll have azureml-core 1.36.0.post2 which is incompatible.
ERROR: azureml-responsibleai 1.37.0 has requirement azureml-dataset-runtime~=1.37.0, but you'll have azureml-dataset-runtime 1.36.0 which is incompatible.
ERROR: azureml-responsibleai 1.37.0 has requirement azureml-interpret~=1.37.0, but you'll have azureml-interpret 1.36.0 which is incompatible.
ERROR: azureml-responsibleai 1.37.0 has requirement azureml-telemetry~=1.37.0, but you'll have azureml-telemetry 1.36.0 which is incompatible.
ERROR: azureml-explain-model 1.37.0 has requirement azureml-interpret~=1.37.0, but you'll have azureml-interpret 1.36.0 which is incompatible.
ERROR: azureml-datadrift 1.37.0 has requirement azureml-core~=1.37.0, but you'll have azureml-core 1.36.0.post2 which is incompatible.
ERROR: azureml-datadrift 1.37.0 has requirement azureml-dataset-runtime[fuse,pandas]~=1.37.0, but you'll have azureml-dataset-runtime 1.36.0 which is incompatible.
ERROR: azureml-datadrift 1.37.0 has requirement azureml-telemetry~=1.37.0, but you'll have azureml-telemetry 1.36.0 which is incompatible.
ERROR: azureml-automl-runtime 1.36.0 has requirement scikit-learn<0.23.0,>=0.19.0, but you'll have scikit-learn 0.24.2 which is incompatible.
ERROR: azureml-automl-dnn-nlp 1.37.0 has requirement azureml-automl-core~=1.37.0, but you'll have azureml-automl-core 1.36.1 which is incompatible.
ERROR: azureml-automl-dnn-nlp 1.37.0 has requirement azureml-automl-runtime~=1.37.0, but you'll have azureml-automl-runtime 1.36.0 which is incompatible.
ERROR: azureml-automl-dnn-nlp 1.37.0 has requirement azureml-core~=1.37.0, but you'll have azureml-core 1.36.0.post2 which is incompatible.
ERROR: azureml-automl-dnn-nlp 1.37.0 has requirement azureml-telemetry~=1.37.0, but you'll have azureml-telemetry 1.36.0 which is incompatible.
ERROR: autokeras 1.0.16.post1 has requirement tensorflow<2.6,>=2.3.0, but you'll have tensorflow 2.1.0 which is incompatible.

**Comment by DawnmarieDesJardins** [comment]
@timahenning - Hello!  Any update on this one?

**Comment by timahenning** [comment]
Hi @Kalyani7744, I was able to reproduce the issue.  It looks like the underlying dependency libraries have been upgraded and a new pip install configuration needs to be created and tested.  We are working on a fix.

**Comment by feaselkl** [comment]
It looks like those update instructions are not necessary and trying to pin the Azure ML version to fix #63 caused an issue once the default version of Azure ML upgraded to 1.37 on compute instances.

For now, I'm commenting out the upgrade commands, as the notebooks will run without them.  If you try this again, please delete and re-create a compute instance as broken upgrade attempts can leave Python in a weird state.
