### ISSUE TITLE
MicrosoftCloudWorkshop.com description needs an update.

### ISSUE THREAD

**Issue by sadukie** [microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics#67]
On MicrosoftCloudWorkshop.com, this MCW shows this:

```
Design a data pipeline solution leveraging Cosmos DB for scalable ingest and global distribution. Use Azure Databricks Delta with a modern data warehouse to reduce risk.
```
However, Azure Databricks is not anywhere in the HOL materials. It looks like it was edited out in [September 2020](https://github.com/microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics/commit/6538488879e102b677fbb6db57489c34a53a92d8).

Azure Databricks Delta was replaced with Azure Synapse Analytics. Perhaps the MicrosoftCloudWorkshop.com description could be:

```
Design a data pipeline solution leveraging the Azure Cosmos DB change feed in concert with the Azure Synapse Analytics to enable a modern data warehouse solution to reduce risk.
```

**Comment by DawnmarieDesJardins** [comment]
Thanks Sarah!  I've updated the library pages - your catch is so appreciated.
